language: node_js

services:
  - docker

node_js:
  - 12

before_install:
  - docker build -t travistest .
  - docker run -d -p 5000:8080 travistest
  - docker ps -a

install:
  - npm install
    
script:
  - npm test